### ISSUE TITLE
SDK7 Visual Tests

### ISSUE THREAD

**Issue by pravusjif** [decentraland/creator-hub#167]
### Tasks
- [ ] [Core Testing Logic](https://github.com/decentraland/creator-hub/issues/165)
- [ ] [Test Case: Test Scene with all visual components](https://github.com/decentraland/sdk/issues/618)
- [ ] [Test Case: Test Scene with all UI Components](https://github.com/decentraland/sdk/issues/525)
- [ ] [Test Case: Test Scene with different Material settings](https://github.com/decentraland/sdk/issues/619)
- [ ] [Test Case: GLTFContainer](https://github.com/decentraland/sdk/issues/620)
